let
    Fonte = #table(
        type table [
            #"CST_ICMS" = text,
            #"DESC_CST" = text,
            #"INICIO" = date,
            #"FIM" = nullable date
        ],
        {
            {"000", "Nacional - Tributada integralmente", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"010", "Nacional - Tributada e com cobrança do ICMS por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"020", "Nacional - Com redução de base de cálculo", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"030", "Nacional - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"040", "Nacional - Isenta", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"041", "Nacional - Não tributada", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"050", "Nacional - Suspensão", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"051", "Nacional - Diferimento", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"060", "Nacional - ICMS cobrado anteriormente por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"070", "Nacional - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"090", "Nacional - Outras", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"100", "Estrangeira - Importação direta - Tributada integralmente", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"110", "Estrangeira - Importação direta - Tributada e com cobrança do ICMS por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"120", "Estrangeira - Importação direta - Com redução de base de cálculo", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"130", "Estrangeira - Importação direta - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"140", "Estrangeira - Importação direta - Isenta", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"141", "Estrangeira - Importação direta - Não tributada", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"150", "Estrangeira - Importação direta - Suspensão", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"151", "Estrangeira - Importação direta - Diferimento", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"160", "Estrangeira - Importação direta - ICMS cobrado anteriormente por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"170", "Estrangeira - Importação direta - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"190", "Estrangeira - Importação direta - Outras", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"200", "Estrangeira - Adquirida no mercado interno - Tributada integralmente", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"210", "Estrangeira - Adquirida no mercado interno - Tributada e com cobrança do ICMS por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"220", "Estrangeira - Adquirida no mercado interno - Com redução de base de cálculo", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"230", "Estrangeira - Adquirida no mercado interno - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"240", "Estrangeira - Adquirida no mercado interno - Isenta", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"241", "Estrangeira - Adquirida no mercado interno - Não tributada", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"250", "Estrangeira - Adquirida no mercado interno - Suspensão", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"251", "Estrangeira - Adquirida no mercado interno - Diferimento", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"260", "Estrangeira - Adquirida no mercado interno - ICMS cobrado anteriormente por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"270", "Estrangeira - Adquirida no mercado interno - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"290", "Estrangeira - Adquirida no mercado interno - Outras", #date(2009, 1, 1), #date(2012, 12, 31)},
            {"101", "Simples Nacional - Tributada pelo Simples Nacional com permissão de crédito", #date(2010, 10, 1), null},
            {"102", "Simples Nacional - Tributada pelo Simples Nacional sem permissão de crédito", #date(2010, 10, 1), #date(2023, 3, 31)},
            {"102", "Para Simples Nacional: Tributada pelo Simples Nacional sem permissão de crédito / Para CST ICMS: Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Tributação monofásica própria sobre combustíveis", #date(2023, 4, 1), null},
            {"103", "Simples Nacional - Isenção do ICMS no Simples Nacional para faixa de receita bruta", #date(2010, 10, 1), null},
            {"201", "Simples Nacional - Tributada pelo Simples Nacional com permissão de crédito e com cobrança do ICMS por substituição tributária", #date(2010, 10, 1), null},
            {"202", "Simples Nacional - Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por substituição tributária", #date(2010, 10, 1), #date(2023, 3, 31)},
            {"202", "Para Simples Nacional: Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por substituição tributária / Para CST ICMS: Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Tributação monofásica própria sobre combustíveis", #date(2023, 4, 1), null},
            {"203", "Simples Nacional - Isenção do ICMS no Simples Nacional para faixa de receita bruta e com cobrança do ICMS por substituição tributária", #date(2010, 10, 1), null},
            {"300", "Simples Nacional - Imune", #date(2010, 10, 1), #date(2012, 12, 31)},
            {"400", "Simples Nacional - Não tributada pelo Simples Nacional", #date(2010, 10, 1), #date(2012, 12, 31)},
            {"500", "Simples Nacional - ICMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação", #date(2010, 10, 1), #date(2012, 12, 31)},
            {"900", "Simples Nacional - Outros", #date(2010, 10, 1), null},
            {"000", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Tributada integralmente", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"010", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"020", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Com redução de base de cálculo", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"030", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"040", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Isenta", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"041", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Não tributada", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"050", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Suspensão", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"051", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Diferimento", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"060", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - ICMS cobrado anteriormente por substituição tributária", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"070", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"090", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Outras", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"000", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Tributada integralmente", #date(2013, 8, 1), null},
            {"010", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 8, 1), null},
            {"020", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Com redução de base de cálculo", #date(2013, 8, 1), null},
            {"030", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 8, 1), null},
            {"040", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Isenta", #date(2013, 8, 1), null},
            {"041", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Não tributada", #date(2013, 8, 1), null},
            {"050", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Suspensão", #date(2013, 8, 1), null},
            {"051", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Diferimento", #date(2013, 8, 1), null},
            {"060", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - ICMS cobrado anteriormente por substituição tributária", #date(2013, 8, 1), null},
            {"070", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 8, 1), null},
            {"090", "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8 da Tabela A - Outras", #date(2013, 8, 1), null},
            {"100", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Tributada integralmente", #date(2013, 1, 1), null},
            {"110", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"120", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Com redução de base de cálculo", #date(2013, 1, 1), null},
            {"130", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"140", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Isenta", #date(2013, 1, 1), null},
            {"141", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Não tributada", #date(2013, 1, 1), null},
            {"150", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Suspensão", #date(2013, 1, 1), null},
            {"151", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Diferimento", #date(2013, 1, 1), null},
            {"160", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - ICMS cobrado anteriormente por substituição tributária", #date(2013, 1, 1), null},
            {"170", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"190", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Outras", #date(2013, 1, 1), null},
            {"200", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Tributada integralmente", #date(2013, 1, 1), null},
            {"210", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"220", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Com redução de base de cálculo", #date(2013, 1, 1), null},
            {"230", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"240", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Isenta", #date(2013, 1, 1), null},
            {"241", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Não tributada", #date(2013, 1, 1), null},
            {"250", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Suspensão", #date(2013, 1, 1), null},
            {"251", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Diferimento", #date(2013, 1, 1), null},
            {"260", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - ICMS cobrado anteriormente por substituição tributária", #date(2013, 1, 1), null},
            {"270", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"290", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Outras", #date(2013, 1, 1), null},
            {"300", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Tributada integralmente", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"310", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"320", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Com redução de base de cálculo", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"330", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"340", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Isenta", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"341", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Não tributada", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"350", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Suspensão", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"351", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Diferimento", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"360", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - ICMS cobrado anteriormente por substituição tributária", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"370", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"390", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a  40% (quarenta por cento) - Outras", #date(2013, 1, 1), #date(2013, 7, 31)},
            {"300", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Tributada integralmente", #date(2013, 8, 1), null},
            {"310", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 8, 1), null},
            {"320", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Com redução de base de cálculo", #date(2013, 8, 1), null},
            {"330", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 8, 1), null},
            {"340", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Isenta", #date(2013, 8, 1), null},
            {"341", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Não tributada", #date(2013, 8, 1), null},
            {"350", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Suspensão", #date(2013, 8, 1), null},
            {"351", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Diferimento", #date(2013, 8, 1), null},
            {"360", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - ICMS cobrado anteriormente por substituição tributária", #date(2013, 8, 1), null},
            {"370", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 8, 1), null},
            {"390", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Outras", #date(2013, 8, 1), null},
            {"400", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/07 - Tributada integralmente", #date(2013, 1, 1), null},
            {"410", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/08 - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"420", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/09 - Com redução de base de cálculo", #date(2013, 1, 1), null},
            {"430", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/10 - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"440", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/11 - Isenta", #date(2013, 1, 1), null},
            {"441", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/12 - Não tributada", #date(2013, 1, 1), null},
            {"450", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/13 - Suspensão", #date(2013, 1, 1), null},
            {"451", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/14 - Diferimento", #date(2013, 1, 1), null},
            {"460", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/15 - ICMS cobrado anteriormente por substituição tributária", #date(2013, 1, 1), null},
            {"470", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/16 - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"490", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/17 - Outras", #date(2013, 1, 1), null},
            {"500", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Tributada integralmente", #date(2013, 1, 1), null},
            {"510", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"520", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Com redução de base de cálculo", #date(2013, 1, 1), null},
            {"530", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"540", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Isenta", #date(2013, 1, 1), null},
            {"541", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Não tributada", #date(2013, 1, 1), null},
            {"550", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Suspensão", #date(2013, 1, 1), null},
            {"551", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Diferimento", #date(2013, 1, 1), null},
            {"560", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - ICMS cobrado anteriormente por substituição tributária", #date(2013, 1, 1), null},
            {"570", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"590", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Outras", #date(2013, 1, 1), null},
            {"600", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Tributada integralmente", #date(2013, 1, 1), null},
            {"610", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"620", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Com redução de base de cálculo", #date(2013, 1, 1), null},
            {"630", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"640", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Isenta", #date(2013, 1, 1), null},
            {"641", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Não tributada", #date(2013, 1, 1), null},
            {"650", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Suspensão", #date(2013, 1, 1), null},
            {"651", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Diferimento", #date(2013, 1, 1), null},
            {"660", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - ICMS cobrado anteriormente por substituição tributária", #date(2013, 1, 1), null},
            {"670", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"690", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Outras", #date(2013, 1, 1), null},
            {"700", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Tributada integralmente", #date(2013, 1, 1), null},
            {"710", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"720", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Com redução de base de cálculo", #date(2013, 1, 1), null},
            {"730", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"740", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Isenta", #date(2013, 1, 1), null},
            {"741", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Não tributada", #date(2013, 1, 1), null},
            {"750", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Suspensão", #date(2013, 1, 1), null},
            {"751", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Diferimento", #date(2013, 1, 1), null},
            {"760", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - ICMS cobrado anteriormente por substituição tributária", #date(2013, 1, 1), null},
            {"770", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 1, 1), null},
            {"790", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Outras", #date(2013, 1, 1), null},
            {"800", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Tributada integralmente", #date(2013, 8, 1), null},
            {"810", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Tributada e com cobrança do ICMS por substituição tributária", #date(2013, 8, 1), null},
            {"820", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Com redução de base de cálculo", #date(2013, 8, 1), null},
            {"830", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Isenta ou não tributada e com cobrança do ICMS por substituição tributária", #date(2013, 8, 1), null},
            {"840", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Isenta", #date(2013, 8, 1), null},
            {"841", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Não tributada", #date(2013, 8, 1), null},
            {"850", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Suspensão", #date(2013, 8, 1), null},
            {"851", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Diferimento", #date(2013, 8, 1), null},
            {"860", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - ICMS cobrado anteriormente por substituição tributária", #date(2013, 8, 1), null},
            {"870", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", #date(2013, 8, 1), null},
            {"890", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Outras", #date(2013, 8, 1), null},
            {"002", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Tributação monofásica própria sobre combustíveis", #date(2023, 4, 1), null},
            {"015", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis", #date(2023, 4, 1), null},
            {"053", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Tributação monofásica sobre combustíveis com recolhimento diferido", #date(2023, 4, 1), null},
            {"061", "Nacional, exceto as indicadas nos códigos 3 a 5 da Tabela A - Tributação monofásica sobre combustíveis cobrada anteriormente", #date(2023, 4, 1), null},
            {"115", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis", #date(2023, 4, 1), null},
            {"153", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Tributação monofásica sobre combustíveis com recolhimento diferido", #date(2023, 4, 1), null},
            {"161", "Estrangeira - Importação direta, exceto a indicada no código 6 da Tabela A - Tributação monofásica sobre combustíveis cobrada anteriormente", #date(2023, 4, 1), null},
            {"215", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis", #date(2023, 4, 1), null},
            {"253", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Tributação monofásica sobre combustíveis com recolhimento diferido", #date(2023, 4, 1), null},
            {"261", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 da Tabela A - Tributação monofásica sobre combustíveis cobrada anteriormente", #date(2023, 4, 1), null},
            {"302", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Tributação monofásica própria sobre combustíveis", #date(2023, 4, 1), null},
            {"315", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis", #date(2023, 4, 1), null},
            {"353", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Tributação monofásica sobre combustíveis com recolhimento diferido", #date(2023, 4, 1), null},
            {"361", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento) - Tributação monofásica sobre combustíveis cobrada anteriormente", #date(2023, 4, 1), null},
            {"402", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/07 - Tributação monofásica própria sobre combustíveis", #date(2023, 4, 1), null},
            {"415", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/07 - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis", #date(2023, 4, 1), null},
            {"453", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/07 - Tributação monofásica sobre combustíveis com recolhimento diferido", #date(2023, 4, 1), null},
            {"461", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/07 - Tributação monofásica sobre combustíveis cobrada anteriormente", #date(2023, 4, 1), null},
            {"502", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Tributação monofásica própria sobre combustíveis", #date(2023, 4, 1), null},
            {"515", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis", #date(2023, 4, 1), null},
            {"553", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Tributação monofásica sobre combustíveis com recolhimento diferido", #date(2023, 4, 1), null},
            {"561", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento) - Tributação monofásica sobre combustíveis cobrada anteriormente", #date(2023, 4, 1), null},
            {"602", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Tributação monofásica própria sobre combustíveis", #date(2023, 4, 1), null},
            {"615", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis", #date(2023, 4, 1), null},
            {"653", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Tributação monofásica sobre combustíveis com recolhimento diferido", #date(2023, 4, 1), null},
            {"661", "Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX - Tributação monofásica sobre combustíveis cobrada anteriormente", #date(2023, 4, 1), null},
            {"702", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Tributação monofásica própria sobre combustíveis", #date(2023, 4, 1), null},
            {"715", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis", #date(2023, 4, 1), null},
            {"753", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Tributação monofásica sobre combustíveis com recolhimento diferido", #date(2023, 4, 1), null},
            {"761", "Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX - Tributação monofásica sobre combustíveis cobrada anteriormente", #date(2023, 4, 1), null},
            {"802", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Tributação monofásica própria sobre combustíveis", #date(2023, 4, 1), null},
            {"815", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis", #date(2023, 4, 1), null},
            {"853", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Tributação monofásica sobre combustíveis com recolhimento diferido", #date(2023, 4, 1), null},
            {"861", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento) - Tributação monofásica sobre combustíveis cobrada anteriormente", #date(2023, 4, 1), null}
        }
    ),
    Final = Fonte
in
    Final