let
    Fonte = #table(
        type table [
            #"CFOP" = text,
            #"Descrição" = text,
            #"Início" = date,
            #"Fim" = nullable date
        ],
        {
            {"1101", "Compra para industrialização", #date(2009, 1, 1), null},
            {"1102", "Compra para comercialização", #date(2009, 1, 1), null},
            {"1111", "Compra para industrialização de mercadoria recebida anteriormente em consignação industrial", #date(2009, 1, 1), null},
            {"1113", "Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil", #date(2009, 1, 1), null},
            {"1116", "Compra para industrialização originada de encomenda para recebimento futuro", #date(2009, 1, 1), null},
            {"1117", "Compra para comercialização originada de encomenda para recebimento futuro", #date(2009, 1, 1), null},
            {"1118", "Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem", #date(2009, 1, 1), null},
            {"1120", "Compra para industrialização, em venda à ordem, já recebida do vendedor remetente", #date(2009, 1, 1), null},
            {"1121", "Compra para comercialização, em venda à ordem, já recebida do vendedor remetente", #date(2009, 1, 1), null},
            {"1122", "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", #date(2009, 1, 1), null},
            {"1124", "Industrialização efetuada por outra empresa", #date(2009, 1, 1), null},
            {"1125", "Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria", #date(2009, 1, 1), null},
            {"1126", "Compra para utilização na prestação de serviço", #date(2009, 1, 1), null},
            {"1151", "Transferência para industrialização", #date(2009, 1, 1), null},
            {"1152", "Transferência para comercialização", #date(2009, 1, 1), null},
            {"1153", "Transferência de energia elétrica para distribuição", #date(2009, 1, 1), null},
            {"1154", "Transferência para utilização na prestação de serviço", #date(2009, 1, 1), null},
            {"1159", "Entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo", #date(2018, 9, 1), null},
            {"1201", "Devolução de venda de produção do estabelecimento", #date(2009, 1, 1), null},
            {"1202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"1202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas nos códigos 1.503, 1.504, 1.505 e 1.506", #date(2022, 6, 1), null},
            {"1203", "Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", #date(2009, 1, 1), null},
            {"1204", "Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", #date(2009, 1, 1), null},
            {"1205", "Anulação de valor relativo à prestação de serviço de comunicação", #date(2009, 1, 1), null},
            {"1206", "Anulação de valor relativo à prestação de serviço de transporte", #date(2009, 1, 1), null},
            {"1207", "Anulação de valor relativo à venda de energia elétrica", #date(2009, 1, 1), null},
            {"1208", "Devolução de produção do estabelecimento, remetida em transferência", #date(2009, 1, 1), null},
            {"1209", "Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência", #date(2009, 1, 1), null},
            {"1251", "Compra de energia elétrica para distribuição ou comercialização", #date(2009, 1, 1), null},
            {"1252", "Compra de energia elétrica por estabelecimento industrial", #date(2009, 1, 1), null},
            {"1253", "Compra de energia elétrica por estabelecimento comercial", #date(2009, 1, 1), null},
            {"1254", "Compra de energia elétrica por estabelecimento prestador de serviço de transporte", #date(2009, 1, 1), null},
            {"1255", "Compra de energia elétrica por estabelecimento prestador de serviço de comunicação", #date(2009, 1, 1), null},
            {"1256", "Compra de energia elétrica por estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"1257", "Compra de energia elétrica para consumo por demanda contratada", #date(2009, 1, 1), null},
            {"1301", "Aquisição de serviço de comunicação para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"1302", "Aquisição de serviço de comunicação por estabelecimento industrial", #date(2009, 1, 1), null},
            {"1303", "Aquisição de serviço de comunicação por estabelecimento comercial", #date(2009, 1, 1), null},
            {"1304", "Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte", #date(2009, 1, 1), null},
            {"1305", "Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica", #date(2009, 1, 1), null},
            {"1306", "Aquisição de serviço de comunicação por estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"1351", "Aquisição de serviço de transporte para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"1352", "Aquisição de serviço de transporte por estabelecimento industrial", #date(2009, 1, 1), null},
            {"1353", "Aquisição de serviço de transporte por estabelecimento comercial", #date(2009, 1, 1), null},
            {"1354", "Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação", #date(2009, 1, 1), null},
            {"1355", "Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica", #date(2009, 1, 1), null},
            {"1356", "Aquisição de serviço de transporte por estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"1360", "Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte.", #date(2009, 1, 1), null},
            {"1401", "Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1403", "Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1406", "Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1407", "Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1408", "Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1409", "Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1410", "Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1411", "Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1414", "Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1415", "Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"1451", "Retorno de animal do estabelecimento produtor", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"1451", "Entrada de animal - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"1452", "Retorno de insumo não utilizado na produção", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"1452", "Entrada de insumo - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"1453", "Retorno do animal ou da produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"1454", "Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"1455", "Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"1456", "Entrada referente a remuneração do produtor no Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"1501", "Entrada de mercadoria recebida com fim específico de exportação", #date(2009, 1, 1), null},
            {"1503", "Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento", #date(2009, 1, 1), null},
            {"1504", "Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros", #date(2009, 1, 1), null},
            {"1505", "Entrada decorrente de devolução simbólica de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.", #date(2009, 1, 1), #date(2018, 8, 31)},
            {"1505", "Entrada decorrente de devolução de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.", #date(2018, 9, 1), null},
            {"1506", "Entrada decorrente de devolução simbólica de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação.", #date(2009, 1, 1), #date(2018, 8, 31)},
            {"1506", "Entrada decorrente de devolução de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação", #date(2018, 9, 1), null},
            {"1551", "Compra de bem para o ativo imobilizado", #date(2009, 1, 1), null},
            {"1552", "Transferência de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"1553", "Devolução de venda de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"1554", "Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento", #date(2009, 1, 1), null},
            {"1555", "Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento", #date(2009, 1, 1), null},
            {"1556", "Compra de material para uso ou consumo", #date(2009, 1, 1), null},
            {"1557", "Transferência de material para uso ou consumo", #date(2009, 1, 1), null},
            {"1601", "Recebimento, por transferência, de crédito de ICMS", #date(2009, 1, 1), null},
            {"1602", "Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS", #date(2009, 1, 1), null},
            {"1603", "Ressarcimento de ICMS retido por substituição tributária", #date(2009, 1, 1), null},
            {"1604", "Lançamento do crédito relativo à compra de bem para o ativo imobilizado", #date(2009, 1, 1), null},
            {"1605", "Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa.", #date(2009, 1, 1), null},
            {"1651", "Compra de combustível ou lubrificante para industrialização subseqüente", #date(2009, 1, 1), null},
            {"1652", "Compra de combustível ou lubrificante para comercialização", #date(2009, 1, 1), null},
            {"1653", "Compra de combustível ou lubrificante por consumidor ou usuário final", #date(2009, 1, 1), null},
            {"1657", "Retorno de remessa de combustível ou lubrificante para venda fora do estabelecimento", #date(2020, 2, 1), null},
            {"1658", "Transferência de combustível e lubrificante para industrialização", #date(2009, 1, 1), null},
            {"1659", "Transferência de combustível e lubrificante para comercialização", #date(2009, 1, 1), null},
            {"1660", "Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente", #date(2009, 1, 1), null},
            {"1661", "Devolução de venda de combustível ou lubrificante destinado à comercialização", #date(2009, 1, 1), null},
            {"1662", "Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final", #date(2009, 1, 1), null},
            {"1663", "Entrada de combustível ou lubrificante para armazenagem", #date(2009, 1, 1), null},
            {"1664", "Retorno de combustível ou lubrificante remetido para armazenagem", #date(2009, 1, 1), null},
            {"1901", "Entrada para industrialização por encomenda", #date(2009, 1, 1), null},
            {"1902", "Retorno de mercadoria remetida para industrialização por encomenda", #date(2009, 1, 1), null},
            {"1903", "Entrada de mercadoria remetida para industrialização e não aplicada no referido processo", #date(2009, 1, 1), null},
            {"1904", "Retorno de remessa para venda fora do estabelecimento", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"1904", "Retorno de remessa para venda fora do estabelecimento, ou qualquer entrada e retorno de remessa efetuada pelo MEI com exceção dos classificados nos códigos 1.202, 1.503, 1.504, 1.505 e 1.506", #date(2022, 6, 1), null},
            {"1905", "Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"1906", "Retorno de mercadoria remetida para depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"1907", "Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"1908", "Entrada de bem por conta de contrato de comodato", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"1908", "Entrada de bem por conta de contrato de comodato ou locação", #date(2019, 12, 1), null},
            {"1909", "Retorno de bem remetido por conta de contrato de comodato", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"1909", "Retorno de bem remetido por conta de contrato de comodato ou locação", #date(2019, 12, 1), null},
            {"1910", "Entrada de bonificação, doação ou brinde", #date(2009, 1, 1), null},
            {"1911", "Entrada de amostra grátis", #date(2009, 1, 1), null},
            {"1912", "Entrada de mercadoria ou bem recebido para demonstração", #date(2009, 1, 1), null},
            {"1913", "Retorno de mercadoria ou bem remetido para demonstração", #date(2009, 1, 1), null},
            {"1914", "Retorno de mercadoria ou bem remetido para exposição ou feira", #date(2009, 1, 1), null},
            {"1915", "Entrada de mercadoria ou bem recebido para conserto ou reparo", #date(2009, 1, 1), null},
            {"1916", "Retorno de mercadoria ou bem remetido para conserto ou reparo", #date(2009, 1, 1), null},
            {"1917", "Entrada de mercadoria recebida em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"1918", "Devolução de mercadoria remetida em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"1919", "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"1920", "Entrada de vasilhame ou sacaria", #date(2009, 1, 1), null},
            {"1921", "Retorno de vasilhame ou sacaria", #date(2009, 1, 1), null},
            {"1922", "Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro", #date(2009, 1, 1), null},
            {"1923", "Entrada de mercadoria recebida do vendedor remetente, em venda à ordem", #date(2009, 1, 1), null},
            {"1924", "Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"1925", "Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"1926", "Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação", #date(2009, 1, 1), null},
            {"1931", "Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço. (Ajuste SINIEF 03/04)", #date(2009, 1, 1), null},
            {"1932", "Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador. (ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"1933", "Aquisição de serviço tributado pelo ISSQN.(ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"1949", "Outra entrada de mercadoria ou prestação de serviço não especificada", #date(2009, 1, 1), null},
            {"2101", "Compra para industrialização", #date(2009, 1, 1), null},
            {"2102", "Compra para comercialização", #date(2009, 1, 1), null},
            {"2111", "Compra para industrialização de mercadoria recebida anteriormente em consignação industrial", #date(2009, 1, 1), null},
            {"2113", "Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil", #date(2009, 1, 1), null},
            {"2116", "Compra para industrialização originada de encomenda para recebimento futuro", #date(2009, 1, 1), null},
            {"2117", "Compra para comercialização originada de encomenda para recebimento futuro", #date(2009, 1, 1), null},
            {"2118", "Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem", #date(2009, 1, 1), null},
            {"2120", "Compra para industrialização, em venda à ordem, já recebida do vendedor remetente", #date(2009, 1, 1), null},
            {"2121", "Compra para comercialização, em venda à ordem, já recebida do vendedor remetente", #date(2009, 1, 1), null},
            {"2122", "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", #date(2009, 1, 1), null},
            {"2124", "Industrialização efetuada por outra empresa", #date(2009, 1, 1), null},
            {"2125", "Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria", #date(2009, 1, 1), null},
            {"2126", "Compra para utilização na prestação de serviço", #date(2009, 1, 1), null},
            {"2151", "Transferência para industrialização", #date(2009, 1, 1), null},
            {"2152", "Transferência para comercialização", #date(2009, 1, 1), null},
            {"2153", "Transferência de energia elétrica para distribuição", #date(2009, 1, 1), null},
            {"2154", "Transferência para utilização na prestação de serviço", #date(2009, 1, 1), null},
            {"2159", "Entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo", #date(2018, 9, 1), null},
            {"2201", "Devolução de venda de produção do estabelecimento", #date(2009, 1, 1), null},
            {"2202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"2202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas nos códigos 2.503, 2.504, 2.505 e 2.506", #date(2022, 6, 1), null},
            {"2203", "Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", #date(2009, 1, 1), null},
            {"2204", "Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", #date(2009, 1, 1), null},
            {"2205", "Anulação de valor relativo à prestação de serviço de comunicação", #date(2009, 1, 1), null},
            {"2206", "Anulação de valor relativo à prestação de serviço de transporte", #date(2009, 1, 1), null},
            {"2207", "Anulação de valor relativo à venda de energia elétrica", #date(2009, 1, 1), null},
            {"2208", "Devolução de produção do estabelecimento, remetida em transferência", #date(2009, 1, 1), null},
            {"2209", "Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência", #date(2009, 1, 1), null},
            {"2251", "Compra de energia elétrica para distribuição ou comercialização", #date(2009, 1, 1), null},
            {"2252", "Compra de energia elétrica por estabelecimento industrial", #date(2009, 1, 1), null},
            {"2253", "Compra de energia elétrica por estabelecimento comercial", #date(2009, 1, 1), null},
            {"2254", "Compra de energia elétrica por estabelecimento prestador de serviço de transporte", #date(2009, 1, 1), null},
            {"2255", "Compra de energia elétrica por estabelecimento prestador de serviço de comunicação", #date(2009, 1, 1), null},
            {"2256", "Compra de energia elétrica por estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"2257", "Compra de energia elétrica para consumo por demanda contratada", #date(2009, 1, 1), null},
            {"2301", "Aquisição de serviço de comunicação para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"2302", "Aquisição de serviço de comunicação por estabelecimento industrial", #date(2009, 1, 1), null},
            {"2303", "Aquisição de serviço de comunicação por estabelecimento comercial", #date(2009, 1, 1), null},
            {"2304", "Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte", #date(2009, 1, 1), null},
            {"2305", "Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica", #date(2009, 1, 1), null},
            {"2306", "Aquisição de serviço de comunicação por estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"2351", "Aquisição de serviço de transporte para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"2352", "Aquisição de serviço de transporte por estabelecimento industrial", #date(2009, 1, 1), null},
            {"2353", "Aquisição de serviço de transporte por estabelecimento comercial", #date(2009, 1, 1), null},
            {"2354", "Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação", #date(2009, 1, 1), null},
            {"2355", "Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica", #date(2009, 1, 1), null},
            {"2356", "Aquisição de serviço de transporte por estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"2401", "Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2403", "Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2406", "Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2407", "Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2408", "Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2409", "Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2410", "Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2411", "Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2414", "Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2415", "Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"2451", "Entrada de animal - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"2452", "Entrada de insumo - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"2453", "Retorno do animal ou da produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"2454", "Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"2455", "Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"2456", "Entrada referente a remuneração do produtor no Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"2501", "Entrada de mercadoria recebida com fim específico de exportação", #date(2009, 1, 1), null},
            {"2503", "Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento", #date(2009, 1, 1), null},
            {"2504", "Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros", #date(2009, 1, 1), null},
            {"2505", "Entrada decorrente de devolução simbólica de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.", #date(2009, 1, 1), #date(2018, 8, 31)},
            {"2505", "Entrada decorrente de devolução de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento", #date(2018, 9, 1), null},
            {"2506", "Entrada decorrente de devolução simbólica de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação.", #date(2009, 1, 1), #date(2018, 8, 31)},
            {"2506", "Entrada decorrente de devolução de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação", #date(2018, 9, 1), null},
            {"2551", "Compra de bem para o ativo imobilizado", #date(2009, 1, 1), null},
            {"2552", "Transferência de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"2553", "Devolução de venda de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"2554", "Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento", #date(2009, 1, 1), null},
            {"2555", "Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento", #date(2009, 1, 1), null},
            {"2556", "Compra de material para uso ou consumo", #date(2009, 1, 1), null},
            {"2557", "Transferência de material para uso ou consumo", #date(2009, 1, 1), null},
            {"2603", "Ressarcimento de ICMS retido por substituição tributária", #date(2009, 1, 1), null},
            {"2651", "Compra de combustível ou lubrificante para industrialização subseqüente", #date(2009, 1, 1), null},
            {"2652", "Compra de combustível ou lubrificante para comercialização", #date(2009, 1, 1), null},
            {"2653", "Compra de combustível ou lubrificante por consumidor ou usuário final", #date(2009, 1, 1), null},
            {"2657", "Retorno de remessa de combustível ou lubrificante para venda fora do estabelecimento", #date(2020, 2, 1), null},
            {"2658", "Transferência de combustível e lubrificante para industrialização", #date(2009, 1, 1), null},
            {"2659", "Transferência de combustível e lubrificante para comercialização", #date(2009, 1, 1), null},
            {"2660", "Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente", #date(2009, 1, 1), null},
            {"2661", "Devolução de venda de combustível ou lubrificante destinado à comercialização", #date(2009, 1, 1), null},
            {"2662", "Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final", #date(2009, 1, 1), null},
            {"2663", "Entrada de combustível ou lubrificante para armazenagem", #date(2009, 1, 1), null},
            {"2664", "Retorno de combustível ou lubrificante remetido para armazenagem", #date(2009, 1, 1), null},
            {"2901", "Entrada para industrialização por encomenda", #date(2009, 1, 1), null},
            {"2902", "Retorno de mercadoria remetida para industrialização por encomenda", #date(2009, 1, 1), null},
            {"2903", "Entrada de mercadoria remetida para industrialização e não aplicada no referido processo", #date(2009, 1, 1), null},
            {"2904", "Retorno de remessa para venda fora do estabelecimento", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"2904", "Retorno de remessa para venda fora do estabelecimento, ou qualquer entrada e retorno de remessa efetuada pelo MEI com exceção dos classificados nos códigos 2.202, 2.503, 2.504, 2.505 e 2.506", #date(2022, 6, 1), null},
            {"2905", "Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"2906", "Retorno de mercadoria remetida para depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"2907", "Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"2908", "Entrada de bem por conta de contrato de comodato", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"2908", "Entrada de bem por conta de contrato de comodato ou locação", #date(2019, 12, 1), null},
            {"2909", "Retorno de bem remetido por conta de contrato de comodato", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"2909", "Retorno de bem remetido por conta de contrato de comodato ou locação", #date(2019, 12, 1), null},
            {"2910", "Entrada de bonificação, doação ou brinde", #date(2009, 1, 1), null},
            {"2911", "Entrada de amostra grátis", #date(2009, 1, 1), null},
            {"2912", "Entrada de mercadoria ou bem recebido para demonstração", #date(2009, 1, 1), null},
            {"2913", "Retorno de mercadoria ou bem remetido para demonstração", #date(2009, 1, 1), null},
            {"2914", "Retorno de mercadoria ou bem remetido para exposição ou feira", #date(2009, 1, 1), null},
            {"2915", "Entrada de mercadoria ou bem recebido para conserto ou reparo", #date(2009, 1, 1), null},
            {"2916", "Retorno de mercadoria ou bem remetido para conserto ou reparo", #date(2009, 1, 1), null},
            {"2917", "Entrada de mercadoria recebida em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"2918", "Devolução de mercadoria remetida em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"2919", "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"2920", "Entrada de vasilhame ou sacaria", #date(2009, 1, 1), null},
            {"2921", "Retorno de vasilhame ou sacaria", #date(2009, 1, 1), null},
            {"2922", "Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro", #date(2009, 1, 1), null},
            {"2923", "Entrada de mercadoria recebida do vendedor remetente, em venda à ordem", #date(2009, 1, 1), null},
            {"2924", "Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"2925", "Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"2931", "Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço. (ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"2932", "Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador. (ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"2933", "Aquisição de serviço tributado pelo ISSQN. (ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"2949", "Outra entrada de mercadoria ou prestação de serviço não especificado", #date(2009, 1, 1), null},
            {"3101", "Compra para industrialização", #date(2009, 1, 1), null},
            {"3102", "Compra para comercialização", #date(2009, 1, 1), null},
            {"3126", "Compra para utilização na prestação de serviço", #date(2009, 1, 1), null},
            {"3127", "Compra para industrialização sob o regime de drawback", #date(2009, 1, 1), null},
            {"3201", "Devolução de venda de produção do estabelecimento", #date(2009, 1, 1), null},
            {"3202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros", #date(2009, 1, 1), null},
            {"3205", "Anulação de valor relativo à prestação de serviço de comunicação", #date(2009, 1, 1), null},
            {"3206", "Anulação de valor relativo à prestação de serviço de transporte", #date(2009, 1, 1), null},
            {"3207", "Anulação de valor relativo à venda de energia elétrica", #date(2009, 1, 1), null},
            {"3211", "Devolução de venda de produção do estabelecimento sob o regime de drawback", #date(2009, 1, 1), null},
            {"3217", "Compra para industrialização sob o regime de ""drawback""", #date(2009, 1, 1), #date(2009, 10, 1)},
            {"3251", "Compra de energia elétrica para distribuição ou comercialização", #date(2009, 1, 1), null},
            {"3301", "Aquisição de serviço de comunicação para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"3351", "Aquisição de serviço de transporte para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"3352", "Aquisição de serviço de transporte por estabelecimento industrial", #date(2009, 1, 1), null},
            {"3353", "Aquisição de serviço de transporte por estabelecimento comercial", #date(2009, 1, 1), null},
            {"3354", "Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação", #date(2009, 1, 1), null},
            {"3355", "Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica", #date(2009, 1, 1), null},
            {"3356", "Aquisição de serviço de transporte por estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"3503", "Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação", #date(2009, 1, 1), null},
            {"3551", "Compra de bem para o ativo imobilizado", #date(2009, 1, 1), null},
            {"3553", "Devolução de venda de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"3556", "Compra de material para uso ou consumo", #date(2009, 1, 1), null},
            {"3651", "Compra de combustível ou lubrificante para industrialização subseqüente", #date(2009, 1, 1), null},
            {"3652", "Compra de combustível ou lubrificante para comercialização", #date(2009, 1, 1), null},
            {"3653", "Compra de combustível ou lubrificante por consumidor ou usuário final", #date(2009, 1, 1), null},
            {"3930", "Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária", #date(2009, 1, 1), null},
            {"3949", "Outra entrada de mercadoria ou prestação de serviço não especificado", #date(2009, 1, 1), null},
            {"5101", "Venda de produção do estabelecimento", #date(2009, 1, 1), null},
            {"5102", "Venda de mercadoria adquirida ou recebida de terceiros", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"5102", "Venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 5.501, 5.502, 5.504 e 5.505", #date(2022, 6, 1), null},
            {"5103", "Venda de produção do estabelecimento, efetuada fora do estabelecimento", #date(2009, 1, 1), null},
            {"5104", "Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", #date(2009, 1, 1), null},
            {"5105", "Venda de produção do estabelecimento que não deva por ele transitar", #date(2009, 1, 1), null},
            {"5106", "Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", #date(2009, 1, 1), null},
            {"5109", "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", #date(2009, 1, 1), null},
            {"5110", "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", #date(2009, 1, 1), null},
            {"5111", "Venda de produção do estabelecimento remetida anteriormente em consignação industrial", #date(2009, 1, 1), null},
            {"5112", "Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial", #date(2009, 1, 1), null},
            {"5113", "Venda de produção do estabelecimento remetida anteriormente em consignação mercantil", #date(2009, 1, 1), null},
            {"5114", "Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil", #date(2009, 1, 1), null},
            {"5115", "Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil", #date(2009, 1, 1), null},
            {"5116", "Venda de produção do estabelecimento originada de encomenda para entrega futura", #date(2009, 1, 1), null},
            {"5117", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura", #date(2009, 1, 1), null},
            {"5118", "Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", #date(2009, 1, 1), null},
            {"5119", "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", #date(2009, 1, 1), null},
            {"5120", "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem", #date(2009, 1, 1), null},
            {"5122", "Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"5123", "Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"5124", "Industrialização efetuada para outra empresa", #date(2009, 1, 1), null},
            {"5125", "Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria", #date(2009, 1, 1), null},
            {"5151", "Transferência de produção do estabelecimento", #date(2009, 1, 1), null},
            {"5152", "Transferência de mercadoria adquirida ou recebida de terceiros", #date(2009, 1, 1), null},
            {"5153", "Transferência de energia elétrica", #date(2009, 1, 1), null},
            {"5155", "Transferência de produção do estabelecimento, que não deva por ele transitar", #date(2009, 1, 1), null},
            {"5156", "Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", #date(2009, 1, 1), null},
            {"5159", "Fornecimento de produção do estabelecimento de ato cooperativo", #date(2018, 9, 1), null},
            {"5160", "Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo", #date(2018, 9, 1), null},
            {"5201", "Devolução de compra para industrialização", #date(2009, 1, 1), null},
            {"5202", "Devolução de compra para comercialização", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"5202", "Devolução de compra para comercialização, ou qualquer devolução de mercadorias efetuada pelo MEI com exceção das classificadas no código 5.503", #date(2022, 6, 1), null},
            {"5205", "Anulação de valor relativo a aquisição de serviço de comunicação", #date(2009, 1, 1), null},
            {"5206", "Anulação de valor relativo a aquisição de serviço de transporte", #date(2009, 1, 1), null},
            {"5207", "Anulação de valor relativo à compra de energia elétrica", #date(2009, 1, 1), null},
            {"5208", "Devolução de mercadoria recebida em transferência para industrialização", #date(2009, 1, 1), null},
            {"5209", "Devolução de mercadoria recebida em transferência para comercialização", #date(2009, 1, 1), null},
            {"5210", "Devolução de compra para utilização na prestação de serviço", #date(2009, 1, 1), null},
            {"5251", "Venda de energia elétrica para distribuição ou comercialização", #date(2009, 1, 1), null},
            {"5252", "Venda de energia elétrica para estabelecimento industrial", #date(2009, 1, 1), null},
            {"5253", "Venda de energia elétrica para estabelecimento comercial", #date(2009, 1, 1), null},
            {"5254", "Venda de energia elétrica para estabelecimento prestador de serviço de transporte", #date(2009, 1, 1), null},
            {"5255", "Venda de energia elétrica para estabelecimento prestador de serviço de comunicação", #date(2009, 1, 1), null},
            {"5256", "Venda de energia elétrica para estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"5257", "Venda de energia elétrica para consumo por demanda contratada", #date(2009, 1, 1), null},
            {"5258", "Venda de energia elétrica a não contribuinte", #date(2009, 1, 1), null},
            {"5301", "Prestação de serviço de comunicação para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"5302", "Prestação de serviço de comunicação a estabelecimento industrial", #date(2009, 1, 1), null},
            {"5303", "Prestação de serviço de comunicação a estabelecimento comercial", #date(2009, 1, 1), null},
            {"5304", "Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte", #date(2009, 1, 1), null},
            {"5305", "Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica", #date(2009, 1, 1), null},
            {"5306", "Prestação de serviço de comunicação a estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"5307", "Prestação de serviço de comunicação a não contribuinte", #date(2009, 1, 1), null},
            {"5351", "Prestação de serviço de transporte para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"5352", "Prestação de serviço de transporte a estabelecimento industrial", #date(2009, 1, 1), null},
            {"5353", "Prestação de serviço de transporte a estabelecimento comercial", #date(2009, 1, 1), null},
            {"5354", "Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação", #date(2009, 1, 1), null},
            {"5355", "Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica", #date(2009, 1, 1), null},
            {"5356", "Prestação de serviço de transporte a estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"5357", "Prestação de serviço de transporte a não contribuinte", #date(2009, 1, 1), null},
            {"5359", "Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal. (ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"5360", "Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte.", #date(2009, 1, 1), null},
            {"5401", "Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto", #date(2009, 1, 1), null},
            {"5402", "Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto", #date(2009, 1, 1), null},
            {"5403", "Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituto", #date(2009, 1, 1), null},
            {"5405", "Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituído", #date(2009, 1, 1), null},
            {"5408", "Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"5409", "Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"5410", "Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"5411", "Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"5412", "Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"5413", "Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária.", #date(2009, 1, 1), null},
            {"5414", "Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"5415", "Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"5451", "Remessa de animal e de insumo para estabelecimento produtor", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"5451", "Remessa de animal - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"5452", "Remessa de insumo - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"5453", "Retorno de animal ou da produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"5454", "Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"5455", "Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"5456", "Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"5501", "Remessa de produção do estabelecimento, com fim específico de exportação", #date(2009, 1, 1), null},
            {"5502", "Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação", #date(2009, 1, 1), null},
            {"5503", "Devolução de mercadoria recebida com fim específico de exportação", #date(2009, 1, 1), null},
            {"5504", "Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.", #date(2009, 1, 1), null},
            {"5505", "Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação", #date(2009, 1, 1), null},
            {"5551", "Venda de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"5552", "Transferência de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"5553", "Devolução de compra de bem para o ativo imobilizado", #date(2009, 1, 1), null},
            {"5554", "Remessa de bem do ativo imobilizado para uso fora do estabelecimento", #date(2009, 1, 1), null},
            {"5555", "Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento", #date(2009, 1, 1), null},
            {"5556", "Devolução de compra de material de uso ou consumo", #date(2009, 1, 1), null},
            {"5557", "Transferência de material de uso ou consumo", #date(2009, 1, 1), null},
            {"5601", "Transferência de crédito de ICMS acumulado", #date(2009, 1, 1), null},
            {"5602", "Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS", #date(2009, 1, 1), null},
            {"5603", "Ressarcimento de ICMS retido por substituição tributária", #date(2009, 1, 1), null},
            {"5605", "Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa. (ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"5606", "Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais.", #date(2009, 1, 1), null},
            {"5651", "Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente", #date(2009, 1, 1), null},
            {"5652", "Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização", #date(2009, 1, 1), null},
            {"5653", "Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final", #date(2009, 1, 1), null},
            {"5654", "Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente", #date(2009, 1, 1), null},
            {"5655", "Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização", #date(2009, 1, 1), null},
            {"5656", "Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final", #date(2009, 1, 1), null},
            {"5657", "Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento", #date(2009, 1, 1), null},
            {"5658", "Transferência de combustível ou lubrificante de produção do estabelecimento", #date(2009, 1, 1), null},
            {"5659", "Transferência de combustível ou lubrificante adquirido ou recebido de terceiro", #date(2009, 1, 1), null},
            {"5660", "Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente", #date(2009, 1, 1), null},
            {"5661", "Devolução de compra de combustível ou lubrificante adquirido para comercialização", #date(2009, 1, 1), null},
            {"5662", "Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final", #date(2009, 1, 1), null},
            {"5663", "Remessa para armazenagem de combustível ou lubrificante", #date(2009, 1, 1), null},
            {"5664", "Retorno de combustível ou lubrificante recebido para armazenagem", #date(2009, 1, 1), null},
            {"5665", "Retorno simbólico de combustível ou lubrificante recebido para armazenagem", #date(2009, 1, 1), null},
            {"5666", "Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem", #date(2009, 1, 1), null},
            {"5667", "Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação", #date(2009, 1, 1), null},
            {"5901", "Remessa para industrialização por encomenda", #date(2009, 1, 1), null},
            {"5902", "Retorno de mercadoria utilizada na industrialização por encomenda", #date(2009, 1, 1), null},
            {"5903", "Retorno de mercadoria recebida para industrialização e não aplicada no referido processo", #date(2009, 1, 1), null},
            {"5904", "Remessa para venda fora do estabelecimento", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"5904", "Remessa para venda fora do estabelecimento, ou qualquer remessa efetuada pelo MEI com exceção das classificadas nos códigos 5.502 e 5.505", #date(2022, 6, 1), null},
            {"5905", "Remessa para depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"5906", "Retorno de mercadoria depositada em depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"5907", "Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"5908", "Remessa de bem por conta de contrato de comodato", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"5908", "Remessa de bem por conta de contrato de comodato ou locação", #date(2019, 12, 1), null},
            {"5909", "Retorno de bem recebido por conta de contrato de comodato", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"5909", "Retorno de bem recebido por conta de contrato de comodato ou locação", #date(2019, 12, 1), null},
            {"5910", "Remessa em bonificação, doação ou brinde", #date(2009, 1, 1), null},
            {"5911", "Remessa de amostra grátis", #date(2009, 1, 1), null},
            {"5912", "Remessa de mercadoria ou bem para demonstração", #date(2009, 1, 1), null},
            {"5913", "Retorno de mercadoria ou bem recebido para demonstração", #date(2009, 1, 1), null},
            {"5914", "Remessa de mercadoria ou bem para exposição ou feira", #date(2009, 1, 1), null},
            {"5915", "Remessa de mercadoria ou bem para conserto ou reparo", #date(2009, 1, 1), null},
            {"5916", "Retorno de mercadoria ou bem recebido para conserto ou reparo", #date(2009, 1, 1), null},
            {"5917", "Remessa de mercadoria em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"5918", "Devolução de mercadoria recebida em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"5919", "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"5920", "Remessa de vasilhame ou sacaria", #date(2009, 1, 1), null},
            {"5921", "Devolução de vasilhame ou sacaria", #date(2009, 1, 1), null},
            {"5922", "Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura", #date(2009, 1, 1), null},
            {"5923", "Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem", #date(2009, 1, 1), #date(2010, 6, 30)},
            {"5924", "Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"5925", "Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"5926", "Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação", #date(2009, 1, 1), null},
            {"5927", "Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração", #date(2009, 1, 1), null},
            {"5928", "Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa", #date(2009, 1, 1), null},
            {"5929", "Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF", #date(2009, 1, 1), #date(2020, 1, 31)},
            {"5931", "Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço", #date(2009, 1, 1), null},
            {"5932", "Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador", #date(2009, 1, 1), null},
            {"5933", "Prestação de serviço tributado pelo ISSQN. (ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"5949", "Outra saída de mercadoria ou prestação de serviço não especificado", #date(2009, 1, 1), null},
            {"6101", "Venda de produção do estabelecimento", #date(2009, 1, 1), null},
            {"6102", "Venda de mercadoria adquirida ou recebida de terceiros", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"6102", "Venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 6.501, 6.502, 6.504 e 6.505", #date(2022, 6, 1), null},
            {"6103", "Venda de produção do estabelecimento, efetuada fora do estabelecimento", #date(2009, 1, 1), null},
            {"6104", "Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", #date(2009, 1, 1), null},
            {"6105", "Venda de produção do estabelecimento que não deva por ele transitar", #date(2009, 1, 1), null},
            {"6106", "Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", #date(2009, 1, 1), null},
            {"6107", "Venda de produção do estabelecimento, destinada a não contribuinte", #date(2009, 1, 1), null},
            {"6108", "Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte", #date(2009, 1, 1), null},
            {"6109", "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", #date(2009, 1, 1), null},
            {"6110", "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", #date(2009, 1, 1), null},
            {"6111", "Venda de produção do estabelecimento remetida anteriormente em consignação industrial", #date(2009, 1, 1), null},
            {"6112", "Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial", #date(2009, 1, 1), null},
            {"6113", "Venda de produção do estabelecimento remetida anteriormente em consignação mercantil", #date(2009, 1, 1), null},
            {"6114", "Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil", #date(2009, 1, 1), null},
            {"6115", "Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil", #date(2009, 1, 1), null},
            {"6116", "Venda de produção do estabelecimento originada de encomenda para entrega futura", #date(2009, 1, 1), null},
            {"6117", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura", #date(2009, 1, 1), null},
            {"6118", "Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", #date(2009, 1, 1), null},
            {"6119", "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", #date(2009, 1, 1), null},
            {"6120", "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem", #date(2009, 1, 1), null},
            {"6122", "Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"6123", "Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"6124", "Industrialização efetuada para outra empresa", #date(2009, 1, 1), null},
            {"6125", "Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria", #date(2009, 1, 1), null},
            {"6151", "Transferência de produção do estabelecimento", #date(2009, 1, 1), null},
            {"6152", "Transferência de mercadoria adquirida ou recebida de terceiros", #date(2009, 1, 1), null},
            {"6153", "Transferência de energia elétrica", #date(2009, 1, 1), null},
            {"6155", "Transferência de produção do estabelecimento, que não deva por ele transitar", #date(2009, 1, 1), null},
            {"6156", "Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", #date(2009, 1, 1), null},
            {"6159", "Fornecimento de produção do estabelecimento de ato cooperativo", #date(2018, 9, 1), null},
            {"6160", "Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo", #date(2018, 9, 1), null},
            {"6201", "Devolução de compra para industrialização", #date(2009, 1, 1), null},
            {"6202", "Devolução de compra para comercialização", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"6202", "Devolução de compra para comercialização, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas no código 6.503", #date(2022, 6, 1), null},
            {"6205", "Anulação de valor relativo a aquisição de serviço de comunicação", #date(2009, 1, 1), null},
            {"6206", "Anulação de valor relativo a aquisição de serviço de transporte", #date(2009, 1, 1), null},
            {"6207", "Anulação de valor relativo à compra de energia elétrica", #date(2009, 1, 1), null},
            {"6208", "Devolução de mercadoria recebida em transferência para industrialização", #date(2009, 1, 1), null},
            {"6209", "Devolução de mercadoria recebida em transferência para comercialização", #date(2009, 1, 1), null},
            {"6210", "Devolução de compra para utilização na prestação de serviço", #date(2009, 1, 1), null},
            {"6251", "Venda de energia elétrica para distribuição ou comercialização", #date(2009, 1, 1), null},
            {"6252", "Venda de energia elétrica para estabelecimento industrial", #date(2009, 1, 1), null},
            {"6253", "Venda de energia elétrica para estabelecimento comercial", #date(2009, 1, 1), null},
            {"6254", "Venda de energia elétrica para estabelecimento prestador de serviço de transporte", #date(2009, 1, 1), null},
            {"6255", "Venda de energia elétrica para estabelecimento prestador de serviço de comunicação", #date(2009, 1, 1), null},
            {"6256", "Venda de energia elétrica para estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"6257", "Venda de energia elétrica para consumo por demanda contratada", #date(2009, 1, 1), null},
            {"6258", "Venda de energia elétrica a não contribuinte", #date(2009, 1, 1), null},
            {"6301", "Prestação de serviço de comunicação para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"6302", "Prestação de serviço de comunicação a estabelecimento industrial", #date(2009, 1, 1), null},
            {"6303", "Prestação de serviço de comunicação a estabelecimento comercial", #date(2009, 1, 1), null},
            {"6304", "Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte", #date(2009, 1, 1), null},
            {"6305", "Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica", #date(2009, 1, 1), null},
            {"6306", "Prestação de serviço de comunicação a estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"6307", "Prestação de serviço de comunicação a não contribuinte", #date(2009, 1, 1), null},
            {"6351", "Prestação de serviço de transporte para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"6352", "Prestação de serviço de transporte a estabelecimento industrial", #date(2009, 1, 1), null},
            {"6353", "Prestação de serviço de transporte a estabelecimento comercial", #date(2009, 1, 1), null},
            {"6354", "Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação", #date(2009, 1, 1), null},
            {"6355", "Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica", #date(2009, 1, 1), null},
            {"6356", "Prestação de serviço de transporte a estabelecimento de produtor rural", #date(2009, 1, 1), null},
            {"6357", "Prestação de serviço de transporte a não contribuinte", #date(2009, 1, 1), null},
            {"6359", "Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal. (ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"6360", "Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte", #date(2009, 1, 1), null},
            {"6401", "Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto", #date(2009, 1, 1), null},
            {"6402", "Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto", #date(2009, 1, 1), null},
            {"6403", "Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto", #date(2009, 1, 1), null},
            {"6404", "Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente", #date(2009, 1, 1), null},
            {"6408", "Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"6409", "Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"6410", "Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"6411", "Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"6412", "Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"6413", "Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"6414", "Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"6415", "Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária", #date(2009, 1, 1), null},
            {"6451", "Remessa de animal - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"6452", "Remessa de insumo - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"6453", "Retorno de animal ou da produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"6454", "Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"6455", "Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"6456", "Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural", #date(2019, 12, 1), null},
            {"6501", "Remessa de produção do estabelecimento, com fim específico de exportação", #date(2009, 1, 1), null},
            {"6502", "Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação", #date(2009, 1, 1), null},
            {"6503", "Devolução de mercadoria recebida com fim específico de exportação", #date(2009, 1, 1), null},
            {"6504", "Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.", #date(2009, 1, 1), null},
            {"6505", "Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação", #date(2009, 1, 1), null},
            {"6551", "Venda de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"6552", "Transferência de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"6553", "Devolução de compra de bem para o ativo imobilizado", #date(2009, 1, 1), null},
            {"6554", "Remessa de bem do ativo imobilizado para uso fora do estabelecimento", #date(2009, 1, 1), null},
            {"6555", "Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento", #date(2009, 1, 1), null},
            {"6556", "Devolução de compra de material de uso ou consumo", #date(2009, 1, 1), null},
            {"6557", "Transferência de material de uso ou consumo", #date(2009, 1, 1), null},
            {"6603", "Ressarcimento de ICMS retido por substituição tributária", #date(2009, 1, 1), null},
            {"6651", "Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente", #date(2009, 1, 1), null},
            {"6652", "Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização", #date(2009, 1, 1), null},
            {"6653", "Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final", #date(2009, 1, 1), null},
            {"6654", "Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente", #date(2009, 1, 1), null},
            {"6655", "Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização", #date(2009, 1, 1), null},
            {"6656", "Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final", #date(2009, 1, 1), null},
            {"6657", "Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento", #date(2009, 1, 1), null},
            {"6658", "Transferência de combustível ou lubrificante de produção do estabelecimento", #date(2009, 1, 1), null},
            {"6659", "Transferência de combustível ou lubrificante adquirido ou recebido de terceiro", #date(2009, 1, 1), null},
            {"6660", "Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente", #date(2009, 1, 1), null},
            {"6661", "Devolução de compra de combustível ou lubrificante adquirido para comercialização", #date(2009, 1, 1), null},
            {"6662", "Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final", #date(2009, 1, 1), null},
            {"6663", "Remessa para armazenagem de combustível ou lubrificante", #date(2009, 1, 1), null},
            {"6664", "Retorno de combustível ou lubrificante recebido para armazenagem", #date(2009, 1, 1), null},
            {"6665", "Retorno simbólico de combustível ou lubrificante recebido para armazenagem", #date(2009, 1, 1), null},
            {"6666", "Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem", #date(2009, 1, 1), null},
            {"6667", "Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação diferente a da que ocorrer o consumo", #date(2009, 1, 1), null},
            {"6901", "Remessa para industrialização por encomenda", #date(2009, 1, 1), null},
            {"6902", "Retorno de mercadoria utilizada na industrialização por encomenda", #date(2009, 1, 1), null},
            {"6903", "Retorno de mercadoria recebida para industrialização e não aplicada no referido processo", #date(2009, 1, 1), null},
            {"6904", "Remessa para venda fora do estabelecimento", #date(2009, 1, 1), #date(2022, 5, 31)},
            {"6904", "Remessa para venda fora do estabelecimento, ou qualquer remessa efetuada pelo MEI com exceção das classificadas nos códigos 6.502 e 6.505", #date(2022, 6, 1), null},
            {"6905", "Remessa para depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"6906", "Retorno de mercadoria depositada em depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"6907", "Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral", #date(2009, 1, 1), null},
            {"6908", "Remessa de bem por conta de contrato de comodato", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"6908", "Remessa de bem por conta de contrato de comodato ou locação", #date(2019, 12, 1), null},
            {"6909", "Retorno de bem recebido por conta de contrato de comodato", #date(2009, 1, 1), #date(2019, 11, 30)},
            {"6909", "Retorno de bem recebido por conta de contrato de comodato ou locação", #date(2019, 12, 1), null},
            {"6910", "Remessa em bonificação, doação ou brinde", #date(2009, 1, 1), null},
            {"6911", "Remessa de amostra grátis", #date(2009, 1, 1), null},
            {"6912", "Remessa de mercadoria ou bem para demonstração", #date(2009, 1, 1), null},
            {"6913", "Retorno de mercadoria ou bem recebido para demonstração", #date(2009, 1, 1), null},
            {"6914", "Remessa de mercadoria ou bem para exposição ou feira", #date(2009, 1, 1), null},
            {"6915", "Remessa de mercadoria ou bem para conserto ou reparo", #date(2009, 1, 1), null},
            {"6916", "Retorno de mercadoria ou bem recebido para conserto ou reparo", #date(2009, 1, 1), null},
            {"6917", "Remessa de mercadoria em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"6918", "Devolução de mercadoria recebida em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"6919", "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial", #date(2009, 1, 1), null},
            {"6920", "Remessa de vasilhame ou sacaria", #date(2009, 1, 1), null},
            {"6921", "Devolução de vasilhame ou sacaria", #date(2009, 1, 1), null},
            {"6922", "Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura", #date(2009, 1, 1), null},
            {"6923", "Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem", #date(2009, 1, 1), #date(2010, 6, 30)},
            {"6924", "Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"6925", "Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente", #date(2009, 1, 1), null},
            {"6929", "Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF", #date(2009, 1, 1), null},
            {"6931", "Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço", #date(2009, 1, 1), null},
            {"6932", "Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador", #date(2009, 1, 1), null},
            {"6933", "Prestação de serviço tributado pelo ISSQN (ajuste sinief 03/04)", #date(2009, 1, 1), null},
            {"6949", "Outra saída de mercadoria ou prestação de serviço não especificado", #date(2009, 1, 1), null},
            {"7101", "Venda de produção do estabelecimento", #date(2009, 1, 1), null},
            {"7102", "Venda de mercadoria adquirida ou recebida de terceiros", #date(2009, 1, 1), null},
            {"7105", "Venda de produção do estabelecimento, que não deva por ele transitar", #date(2009, 1, 1), null},
            {"7106", "Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", #date(2009, 1, 1), null},
            {"7127", "Venda de produção do estabelecimento sob o regime de drawback", #date(2009, 1, 1), null},
            {"7201", "Devolução de compra para industrialização", #date(2009, 1, 1), null},
            {"7202", "Devolução de compra para comercialização", #date(2009, 1, 1), null},
            {"7205", "Anulação de valor relativo à aquisição de serviço de comunicação", #date(2009, 1, 1), null},
            {"7206", "Anulação de valor relativo a aquisição de serviço de transporte", #date(2009, 1, 1), null},
            {"7207", "Anulação de valor relativo à compra de energia elétrica", #date(2009, 1, 1), null},
            {"7210", "Devolução de compra para utilização na prestação de serviço", #date(2009, 1, 1), null},
            {"7211", "Devolução de compras para industrialização sob o regime de drawback", #date(2009, 1, 1), null},
            {"7251", "Venda de energia elétrica para o exterior", #date(2009, 1, 1), null},
            {"7301", "Prestação de serviço de comunicação para execução de serviço da mesma natureza", #date(2009, 1, 1), null},
            {"7358", "Prestação de serviço de transporte", #date(2009, 1, 1), null},
            {"7501", "Exportação de mercadorias recebidas com fim específico de exportação", #date(2009, 1, 1), null},
            {"7504", "Exportação de mercadoria que foi objeto de formação de lote de exportação", #date(2018, 9, 1), null},
            {"7551", "Venda de bem do ativo imobilizado", #date(2009, 1, 1), null},
            {"7553", "Devolução de compra de bem para o ativo imobilizado", #date(2009, 1, 1), null},
            {"7556", "Devolução de compra de material de uso ou consumo", #date(2009, 1, 1), null},
            {"7651", "Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente", #date(2009, 1, 1), null},
            {"7654", "Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente", #date(2009, 1, 1), null},
            {"7667", "Venda de combustível ou lubrificante a consumidor ou usuário final", #date(2009, 1, 1), null},
            {"7930", "Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária", #date(2009, 1, 1), null},
            {"7949", "Outra saída de mercadoria ou prestação de serviço não especificado", #date(2009, 1, 1), null},
            {"1934", "Entrada simbólica de mercadoria recebida para depósito fechado ou armazém geral", #date(2010, 7, 1), null},
            {"2934", "Entrada simbólica de mercadoria recebida para depósito fechado ou armazém geral", #date(2010, 7, 1), null},
            {"5923", "Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado", #date(2010, 7, 1), null},
            {"5934", "Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado", #date(2010, 7, 1), null},
            {"6923", "Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado", #date(2010, 7, 1), null},
            {"6934", "Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado", #date(2010, 7, 1), null},
            {"1128", "Compra para utilização na prestação de serviço sujeita ao ISSQN", #date(2011, 1, 1), null},
            {"2128", "Compra para utilização na prestação de serviço sujeita ao ISSQN", #date(2011, 1, 1), null},
            {"3128", "Compra para utilização na prestação de serviço sujeita ao ISSQN", #date(2011, 1, 1), null},
            {"1212", "Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)", #date(2016, 4, 1), null},
            {"2212", "Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)", #date(2016, 4, 1), null},
            {"3129", "Compra para industrialização sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)", #date(2016, 4, 1), null},
            {"3212", "Devolução de venda no mercado externo de mercadoria industrializada sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)", #date(2016, 4, 1), null},
            {"5129", "Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped", #date(2016, 4, 1), null},
            {"6129", "Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)", #date(2016, 4, 1), null},
            {"7129", "Venda de produção do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)", #date(2016, 4, 1), null},
            {"7212", "Devolução de compras para industrialização sob o regime de Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)", #date(2016, 4, 1), null},
            {"1131", "Entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, decorrente de operação de ato cooperativo.", #date(2018, 1, 1), null},
            {"1132", "Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização", #date(2018, 1, 1), null},
            {"1135", "Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização.", #date(2018, 1, 1), null},
            {"1213", "Devolução de remessa de produção do estabelecimento com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.", #date(2018, 1, 1), null},
            {"1214", "Devolução de fixação de preço de produção do estabelecimento produtor, de ato cooperativo.", #date(2018, 1, 1), null},
            {"2131", "Entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, decorrente de operação de ato cooperativo.", #date(2018, 1, 1), null},
            {"2132", "Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização.", #date(2018, 1, 1), null},
            {"2135", "Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização.", #date(2018, 1, 1), null},
            {"2213", "Devolução de remessa de produção do estabelecimento com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.", #date(2018, 1, 1), null},
            {"2214", "Devolução de fixação de preço de produção do estabelecimento produtor, de ato cooperativo.", #date(2018, 1, 1), null},
            {"5131", "Remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, de ato cooperativo.", #date(2018, 1, 1), null},
            {"5132", "Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço de ato cooperativo.", #date(2018, 1, 1), null},
            {"5213", "Devolução de entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.", #date(2018, 1, 1), null},
            {"5214", "Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para comercialização.", #date(2018, 1, 1), null},
            {"5215", "Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para industrialização.", #date(2018, 1, 1), null},
            {"6131", "Remessa de produção de estabelecimento, com previsão de posterior ajuste ou fixação de preço de ato cooperativo.", #date(2018, 1, 1), null},
            {"6132", "Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço ou fixação de preço de ato cooperativo.", #date(2018, 1, 1), null},
            {"6213", "Devolução de entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.", #date(2018, 1, 1), null},
            {"6214", "Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para comercialização.", #date(2018, 1, 1), null},
            {"6215", "Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo para industrialização.", #date(2018, 1, 1), null},
            {"1215", "Devolução de fornecimento de produção do estabelecimento de ato cooperativo", #date(2019, 5, 1), null},
            {"1216", "Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo", #date(2019, 5, 1), null},
            {"2215", "Devolução de fornecimento de produção do estabelecimento de ato cooperativo", #date(2019, 5, 1), null},
            {"2216", "Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo", #date(2019, 5, 1), null},
            {"5216", "Devolução de entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo", #date(2019, 5, 1), null},
            {"6216", "Devolução de entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo", #date(2019, 5, 1), null},
            {"5929", "Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também acobertada por documento fiscal do varejo", #date(2020, 2, 1), null},
            {"3552", "Entrada de produtos destinados ao uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior", #date(2021, 6, 1), null},
            {"3667", "Entrada de combustível ou lubrificante para consumo final, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior", #date(2021, 6, 1), null},
            {"7552", "Saída de produtos destinados ao uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior", #date(2021, 6, 1), null}
        }
    ),
    Final = Fonte
in
    Final